### ISSUE TITLE
Decrypt error: "AssertionError"

### ISSUE THREAD

**Issue by sgulls** [nlscc/samloader#45] opened 2021-04-07 16:42 UTC
```
python3  -m samloader -m SM-G996U1 -r XAA decrypt -v G996U1UEU2AUC8/G996U1OYM2AUC8/G996U1UEU2AUC8/G996U1U
EU2AUC8 -V 4 -i ./SM-G996U1_1_20210319175336_uz83oofj1x_fac.zip.enc4 -o ./SM-G996U1_1_20210319175336_uz83oofj1x_fac.zip
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/default/.local/lib/python3.9/site-packages/samloader/__main__.py", line 6, in <module>
    main()
  File "/home/default/.local/lib/python3.9/site-packages/samloader/main.py", line 77, in main
    crypt.decrypt_progress(inf, outf, key, length)
  File "/home/default/.local/lib/python3.9/site-packages/samloader/crypt.py", line 33, in decrypt_progress
    assert length % 16 == 0
AssertionError
```
Tried on both python 3.9 and 3.8 on both Linux/Debian 10 and macOS big sur

**Comment by nlscc** [comment] 2021-04-09 01:03
i think your file may be corrupted. the length should be 6439289024 bytes which is divisible by 16 and doesn't throw an error.
Try downloading it again and make sure the download isn't interrupted:
```
samloader -m SM-G996U1 -r XAA download -v G996U1UEU2AUC8/G996U1OYM2AUC8/G996U1UEU2AUC8/G996U1UEU2AUC8 -O .
```

**Comment by nlscc** [comment] 2021-05-21 22:27
closing because failed to reproduce

**Closed by nlscc** 2021-05-21 22:27 UTC
