### ISSUE TITLE
Erro when installing

### ISSUE THREAD

**Issue by b0xBR** [nlscc/samloader#10] opened 2020-09-27 16:10 UTC
failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\fayet\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\fayet\\AppData\\Local\\Temp\\pip-install-yzlbpcr1\\pycrypto\\setup.py'"'"'; __file__='"'"'C:\\Users\\fayet\\AppData\\Local\\Temp\\pip-install-yzlbpcr1\\pycrypto\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\fayet\AppData\Local\Temp\pip-record-txr2yofa\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\fayet\appdata\local\programs\python\python39\Include\pycrypto' Check the logs for full command output.

Any idea?

**Comment by nlscc** [comment] 2020-09-27 16:12
Please post full reproduction steps

**Comment by nlscc** [comment] 2020-09-29 22:46
Closing because I removed pycrypto and replaced with pycryptodome in the latest version and that error references pycrypto (I have seen that package cause trouble on Windows)

**Closed by nlscc** 2020-09-29 22:46 UTC
